version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:10
    working_directory: ~/spideo-challenge

    steps:
      - checkout
      - restore_cache:
          keys:
            - spideo-challenge-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spideo-challenge-{{ checksum "pom.xml" }}
      - run: mvn -Dmaven.test.skip=true clean package
      # How to use Docker in CircleCi https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker
          command: |
            set -x
            VER="19.03.4-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: docker build -t test:latest .
      - store_artifacts:
          path: target/classes
          destination: spideo-challenge

  test:
    docker:
      - image: circleci/openjdk:10
    working_directory: ~/spideo-challenge

    steps:
      - checkout
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spideo-challenge-{{ checksum "pom.xml" }}
      - run: mvn test